#!/bin/bash
read -p "`echo $'\n📦  '`Enter your Google Express email: " username
read -s -p "`echo $'📦  '`Enter your Google Express password: " password
read -p "`echo $'\n📦  '`Enter a two-factor auth code (if your Google account has two factor auth enabled): " authcode

casperjs phantomcheerios.js $username $password $authcode